[workspace]
resolver = "3"
members = [
    "crates/arnes-core",
    "crates/arnes-tui",
    "crates/arnes-acp",
]

[workspace.dependencies]
agent-rig           = { git = "https://github.com/andreban/agent-rig", branch = "main" }
async-trait         = "0.1"
futures-util        = "0.3"
schemars            = "1"
serde               = { version = "1", features = ["derive"] }
serde_json          = "1"
tokio-util          = { version = "0.7" }
tracing             = "0.1"
tracing-subscriber  = { version = "0.3", features = ["fmt", "env-filter"] }
uuid                = { version = "1", features = ["v7"] }
